create table items
(
	AuditNum varchar(20) primary key,
	StoreNumber varchar(2),
	IDNumber varchar(20),
	Active varchar(5),
	ItemDesc varchar(150),
	DeptAudit varchar(20),
	VenderAudit varchar(20),
	VenderPart varchar(10),
	TaxCode numeric(1,0),
	OnHand varchar(5),
	Reorder varchar(5),
	Restock varchar(5),
	Cost numeric(12,2),
	Retail numeric(12,2),
	SoldDol varchar(10),
	SoldNum varchar(10),
	PriceMethod varchar(10),
	ListPrice varchar(5),
	MarginMarkup varchar(5),
	ListPercent varchar(5),
	CostPercent varchar(5),
	Vol1Desc varchar(5),
	Vol1Qty varchar(5),
	Vol2Retail varchar(5),
	Vol2Desc varchar(5),
	Vol2Qty varchar(5),
	Vol3Retail varchar(5),
	Vol3Desc varchar(5),
	Vol3Qty varchar(5),
	Vol1Retail varchar(5),
	Vol4Desc varchar(5),
	Vol4Qty varchar(5),
	Vol4Retail varchar(5),
	ForceVolume varchar(5),
	PerUnitLabel varchar(5),
	PerUnitAmount varchar(5),
	LastPurchaseDate date,
	LastPurchaseTime time,
	BSTCashDefault varchar(5),
	BSTCreditDefault varchar(5),
	BSTAdded varchar(5),
)